name = "FlexiChains"
uuid = "4a37a8b9-6e57-4b92-8664-298d46e639f7"
authors = ["Penelope Yong <penelopeysm@gmail.com>"]
version = "0.3.2"

[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
AbstractPPL = "7a57a42e-76ec-4ea3-a279-07e840d6d9cf"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
MCMCDiagnosticTools = "be115224-59cd-429b-ad48-344e309966f0"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
PosteriorDB = "1c4bc282-d2f5-44f9-b6d1-8c4424a23ad4"
PosteriorStats = "7f36be82-ad55-44ba-a5c0-b8b5480d7aa5"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[extensions]
FlexiChainsComponentArraysExt = ["ComponentArrays"]
FlexiChainsDynamicPPLExt = ["DynamicPPL", "Random", "DimensionalData", "OrderedCollections"]
FlexiChainsMCMCChainsExt = ["MCMCChains", "OrderedCollections"]
FlexiChainsMakieExt = ["Makie"]
FlexiChainsPosteriorDBExt = ["PosteriorDB", "OrderedCollections"]
FlexiChainsPosteriorStatsExt = ["PosteriorStats"]
FlexiChainsRecipesBaseExt = ["RecipesBase", "StatsBase"]
FlexiChainsTuringExt = ["Turing", "PrecompileTools", "OrderedCollections"]

[compat]
AbstractMCMC = "5.10"
AbstractPPL = "0.13.5"
ComponentArrays = "0.15"
DimensionalData = "0.29.24"
DocStringExtensions = "0.9"
DynamicPPL = "0.39"
Makie = "0.24"
MCMCChains = "6, 7"
MCMCDiagnosticTools = "0.3.15"
OrderedCollections = "1"
PosteriorDB = "0.6"
PosteriorStats = "0.4"
PrecompileTools = "1.2.1"
Printf = "1"
Random = "1"
RecipesBase = "1.3.4"
Statistics = "1"
StatsBase = "0.34.6"
Turing = "0.42"
julia = "1.10.8"
